import {Box, Button, Card, Stack, Text} from "@chakra-ui/react";

export default function JoinQuickCheck(){
    return(
        <Stack
            paddingX="201px"
            paddingY="215px"
            justify="flex-start"
            align="flex-start"
            spacing="10px"
            width="1512px"
            height="1020px"
            maxWidth="100%"
            background="#FFFFFF"
        >
            <Stack
                justify="flex-start"
                align="center"
                spacing="93px"
                width="1059px"
                maxWidth="100%"
            >
                <Stack
                    justify="flex-start"
                    align="center"
                    spacing="20px"
                    width="822px"
                    maxWidth="100%"
                >
                    <Text
                        fontFamily="Inter"
                        fontWeight="bold"
                        fontSize="65px"
                        color="#313131"
                        height="85px"
                        alignSelf="stretch"
                        textAlign="center"
                    >
                        Join Quick Check
                    </Text>
                    <Text
                        fontFamily="Inter"
                        fontWeight="medium"
                        fontSize="24px"
                        color="#707070"
                        height="39px"
                        alignSelf="stretch"
                        textAlign="center"
                    >
                        Start increasing your productivity today !
                    </Text>
                </Stack>
                <Stack
                    direction="row"
                    justify="flex-start"
                    align="center"
                    spacing="103px"
                    alignSelf="stretch"
                >
                    <Stack
                        justify="flex-start"
                        align="flex-start"
                        spacing="39px"
                        width="467px"
                        maxWidth="100%"
                    >
                        <Stack
                            direction="row"
                            justify="flex-start"
                            align="flex-start"
                            spacing="11px"
                            alignSelf="stretch"
                        >
                            <Stack
                                paddingX="13px"
                                paddingY="14px"
                                borderRadius="5px"
                                justify="flex-start"
                                align="flex-start"
                                spacing="10px"
                                width="47px"
                                height="47px"
                                background="#7E3BB5"
                            />
                            <Stack
                                justify="flex-start"
                                align="flex-start"
                                spacing="4px"
                                width="409px"
                                maxWidth="100%"
                            >
                                <Text
                                    fontFamily="Inter"
                                    fontWeight="bold"
                                    fontSize="24px"
                                    color="#313131"
                                    height="30px"
                                    alignSelf="stretch"
                                >
                                    Speed up your meetings
                                </Text>
                                <Text
                                    fontFamily="Inter"
                                    lineHeight="1.38"
                                    fontWeight="semibold"
                                    fontSize="16px"
                                    color="#707070"
                                    height="43px"
                                    alignSelf="stretch"
                                >
                                    With just one click, attend your meetings with ease and
                                    efficiency.
                                </Text>
                            </Stack>
                        </Stack>
                        <Stack
                            direction="row"
                            justify="flex-start"
                            align="flex-start"
                            spacing="11px"
                            alignSelf="stretch"
                        >
                            <Stack
                                paddingX="13px"
                                paddingY="14px"
                                borderRadius="5px"
                                justify="flex-start"
                                align="flex-start"
                                spacing="10px"
                                width="47px"
                                height="47px"
                                background="#7E3BB5"
                            />
                            <Stack
                                justify="flex-start"
                                align="flex-start"
                                spacing="4px"
                                width="409px"
                                maxWidth="100%"
                            >
                                <Text
                                    fontFamily="Inter"
                                    fontWeight="bold"
                                    fontSize="24px"
                                    color="#313131"
                                    height="30px"
                                    alignSelf="stretch"
                                >
                                    Best classroom toolbox
                                </Text>
                                <Text
                                    fontFamily="Inter"
                                    lineHeight="1.38"
                                    fontWeight="semibold"
                                    fontSize="16px"
                                    color="#707070"
                                    height="43px"
                                    alignSelf="stretch"
                                >
                                    No more need to download 10 apps just to be equipped for class,
                                    everything is in there.
                                </Text>
                            </Stack>
                        </Stack>
                        <Stack
                            direction="row"
                            justify="flex-start"
                            align="flex-start"
                            spacing="11px"
                            alignSelf="stretch"
                        >
                            <Stack
                                padding="13px"
                                borderRadius="5px"
                                direction="row"
                                justify="flex-start"
                                align="center"
                                spacing="10px"
                                width="47px"
                                height="47px"
                                background="#7E3BB5"
                            />
                            <Stack
                                justify="flex-start"
                                align="flex-start"
                                spacing="4px"
                                width="409px"
                                maxWidth="100%"
                            >
                                <Text
                                    fontFamily="Inter"
                                    fontWeight="bold"
                                    fontSize="24px"
                                    color="#313131"
                                    height="30px"
                                    alignSelf="stretch"
                                >
                                    Support Quick Check
                                </Text>
                                <Text
                                    fontFamily="Inter"
                                    lineHeight="1.38"
                                    fontWeight="semibold"
                                    fontSize="16px"
                                    color="#707070"
                                    height="43px"
                                    alignSelf="stretch"
                                >
                                    Every sign-up is the beginning of a trust relationship, your
                                    belief of Quick Check
                                </Text>
                            </Stack>
                        </Stack>
                    </Stack>
                    <Stack
                        paddingY="31px"
                        borderRadius="15px"
                        justify="flex-start"
                        align="flex-start"
                        spacing="10px"
                        width="489px"
                        height="352px"
                        maxWidth="100%"
                        background="#FBFBFB"
                        boxShadow="0px 1px 4px 0px rgba(0, 0, 0, 0.25)"
                    >
                        <Stack
                            justify="flex-start"
                            align="center"
                            spacing="27px"
                            width="489px"
                            maxWidth="100%"
                        >
                            <Stack
                                justify="flex-start"
                                align="center"
                                spacing="19px"
                                alignSelf="stretch"
                            >
                                <Stack
                                    direction="row"
                                    justify="flex-start"
                                    align="center"
                                    spacing="101px"
                                >
                                    <Stack
                                        justify="flex-start"
                                        align="flex-start"
                                        spacing="0px"
                                        width="133px"
                                    >
                                        <Text
                                            fontFamily="Inter"
                                            fontWeight="semibold"
                                            fontSize="24px"
                                            color="#313131"
                                            height="30px"
                                            alignSelf="stretch"
                                        >
                                            Basic
                                        </Text>
                                        <Text
                                            fontFamily="Inter"
                                            lineHeight="1.57"
                                            fontWeight="medium"
                                            fontSize="14px"
                                            color="#707070"
                                            height="29px"
                                            alignSelf="stretch"
                                        >
                                            With all features
                                        </Text>
                                    </Stack>
                                    <Stack
                                        direction="row"
                                        justify="flex-start"
                                        align="flex-start"
                                        spacing="0px"
                                    >
                                        <Text
                                            fontFamily="Inter"
                                            fontWeight="semibold"
                                            fontSize="45px"
                                            color="#313131"
                                            width="85px"
                                            height="30px"
                                        >
                                            $10
                                        </Text>
                                        <Text
                                            fontFamily="Inter"
                                            lineHeight="1.57"
                                            fontWeight="medium"
                                            fontSize="14px"
                                            color="#707070"
                                            width="113px"
                                            height="26px"
                                        >
                                            per user / month
                                        </Text>
                                    </Stack>
                                </Stack>
                                <Stack
                                    justify="flex-start"
                                    align="center"
                                    spacing="29px"
                                    alignSelf="stretch"
                                >
                                    <Box height="1px" alignSelf="stretch" background="#EDEDED" />
                                    <Stack
                                        justify="flex-start"
                                        align="flex-end"
                                        spacing="21px"
                                        width="393.25px"
                                        maxWidth="100%"
                                    >
                                        <Text
                                            fontFamily="Inter"
                                            fontWeight="semibold"
                                            fontSize="14px"
                                            color="#313131"
                                            height="18px"
                                            alignSelf="stretch"
                                        >
                                            FEATURES
                                        </Text>
                                        <Stack
                                            justify="flex-start"
                                            align="flex-start"
                                            spacing="15px"
                                            width="376px"
                                            maxWidth="100%"
                                        >
                                            <Stack
                                                direction="row"
                                                justify="flex-start"
                                                align="center"
                                                spacing="73px"
                                                alignSelf="stretch"
                                            >
                                                <Stack
                                                    direction="row"
                                                    justify="flex-start"
                                                    align="center"
                                                    spacing="6px"
                                                >
                                                    <Text
                                                        fontFamily="Inter"
                                                        lineHeight="1.57"
                                                        fontWeight="medium"
                                                        fontSize="14px"
                                                        color="#707070"
                                                        width="133px"
                                                        height="18px"
                                                    >
                                                        With all features
                                                    </Text>
                                                </Stack>
                                                <Stack
                                                    direction="row"
                                                    justify="flex-start"
                                                    align="center"
                                                    spacing="6px"
                                                >
                                                    <Text
                                                        fontFamily="Inter"
                                                        lineHeight="1.57"
                                                        fontWeight="medium"
                                                        fontSize="14px"
                                                        color="#707070"
                                                        width="133px"
                                                        height="18px"
                                                    >
                                                        With all features
                                                    </Text>
                                                </Stack>
                                            </Stack>
                                            <Stack
                                                direction="row"
                                                justify="flex-start"
                                                align="center"
                                                spacing="73px"
                                                alignSelf="stretch"
                                            >
                                                <Stack
                                                    direction="row"
                                                    justify="flex-start"
                                                    align="center"
                                                    spacing="6px"
                                                >
                                                    <Text
                                                        fontFamily="Inter"
                                                        lineHeight="1.57"
                                                        fontWeight="medium"
                                                        fontSize="14px"
                                                        color="#707070"
                                                        width="133px"
                                                        height="18px"
                                                    >
                                                        With all features
                                                    </Text>
                                                </Stack>
                                                <Stack
                                                    direction="row"
                                                    justify="flex-start"
                                                    align="center"
                                                    spacing="6px"
                                                >
                                                    <Text
                                                        fontFamily="Inter"
                                                        lineHeight="1.57"
                                                        fontWeight="medium"
                                                        fontSize="14px"
                                                        color="#707070"
                                                        width="133px"
                                                        height="18px"
                                                    >
                                                        With all features
                                                    </Text>
                                                </Stack>
                                            </Stack>
                                        </Stack>
                                    </Stack>
                                    <Box height="1px" alignSelf="stretch" background="#EDEDED" />
                                </Stack>
                            </Stack>
                            <Stack
                                paddingX="160px"
                                paddingY="7px"
                                borderRadius="5px"
                                direction="row"
                                justify="center"
                                align="center"
                                spacing="10px"
                                width="428px"
                                height="35px"
                                maxWidth="100%"
                                background="#7E3BB5"
                                boxShadow="0px 4px 4px 0px rgba(0, 0, 0, 0.25)"
                            >
                                <Text
                                    fontFamily="Inter"
                                    fontWeight="medium"
                                    fontSize="16px"
                                    color="#F9F9F9"
                                    textAlign="center"
                                >
                                    Start free trial
                                </Text>
                            </Stack>
                        </Stack>
                    </Stack>
                </Stack>
            </Stack>
        </Stack>

)
}