import {Box, Button, Code, Menu, Stack, Text, Tooltip} from "@chakra-ui/react";

export default function SneakPeek(){
    return(
        <Stack
            paddingX="54px"
            justify="flex-end"
            align="center"
            spacing="10px"
            width="1512px"
            height="1006px"
            maxWidth="100%"
            background="#FFFFFF"
        >
            <Stack
                justify="flex-start"
                align="center"
                spacing="56px"
                width="1404px"
                maxWidth="100%"
            >
                <Stack
                    justify="flex-start"
                    align="center"
                    spacing="16px"
                    width="822px"
                    maxWidth="100%"
                >
                    <Text
                        fontFamily="Inter"
                        fontWeight="bold"
                        fontSize="65px"
                        color="#313131"
                        height="78px"
                        alignSelf="stretch"
                        textAlign="center"
                    >
                        <span>Less waste. More </span>
                        <Box as="span" color="#7E3BB5">
                            speed
                        </Box>
                    </Text>
                    <Text
                        fontFamily="Inter"
                        fontWeight="semibold"
                        fontSize="24px"
                        color="#707070"
                        width="508px"
                        height="79px"
                        maxWidth="100%"
                        textAlign="center"
                    >
                        Spend less time doing attendance and more time teaching class
                    </Text>
                </Stack>
                <Stack
                    direction="row"
                    justify="flex-start"
                    align="center"
                    spacing="0px"
                    alignSelf="stretch"
                >
                    <Stack
                        paddingX="55px"
                        paddingY="59px"
                        borderRadius="10px"
                        justify="flex-start"
                        align="flex-start"
                        spacing="10px"
                        width="702px"
                        height="689px"
                        maxWidth="100%"
                        background="#FBFBFB"
                        boxShadow="0px 4px 4px 0px rgba(0, 0, 0, 0.25)"
                    >
                        <Stack
                            justify="flex-start"
                            align="center"
                            spacing="63px"
                            width="591.44px"
                            maxWidth="100%"
                        >
                            <Stack
                                paddingX="20px"
                                paddingY="7px"
                                borderRadius="10px"
                                justify="flex-start"
                                align="flex-start"
                                spacing="10px"
                                width="326px"
                                height="136px"
                                maxWidth="100%"
                                background="#FFFFFF"
                                boxShadow="0px 1px 4px 0px rgba(0, 0, 0, 0.25)"
                            >
                                <Stack
                                    direction="row"
                                    justify="flex-start"
                                    align="flex-start"
                                    spacing="15px"
                                >
                                    <Stack
                                        justify="center"
                                        align="flex-start"
                                        spacing="13px"
                                        height="121px"
                                    >
                                        <Stack
                                            justify="flex-start"
                                            align="center"
                                            spacing="9px"
                                            width="218px"
                                        >
                                            <Stack
                                                justify="flex-start"
                                                align="flex-start"
                                                spacing="4px"
                                                alignSelf="stretch"
                                            >
                                                <Text
                                                    fontFamily="Inter"
                                                    fontWeight="medium"
                                                    fontSize="20px"
                                                    color="#313131"
                                                    alignSelf="stretch"
                                                >
                                                    CS 3337 - Prof. Abalos
                                                </Text>
                                                <Text
                                                    fontFamily="Inter"
                                                    fontWeight="medium"
                                                    fontSize="18px"
                                                    color="#313131"
                                                    alignSelf="stretch"
                                                >
                                                    <span>Friday 10/15 Code : </span>
                                                    <Box as="span" fontWeight="bold" color="#7E3BB5">
                                                        519982
                                                    </Box>
                                                </Text>
                                            </Stack>
                                            <Stack
                                                paddingX="7px"
                                                paddingY="8px"
                                                borderRadius="8px"
                                                direction="row"
                                                justify="center"
                                                align="center"
                                                spacing="10px"
                                                width="153px"
                                                height="38px"
                                                background="#7E3BB5"
                                                boxShadow="0px 4px 4px 0px rgba(0, 0, 0, 0.25)"
                                            >
                                                <Text
                                                    fontFamily="Inter"
                                                    fontWeight="medium"
                                                    fontSize="18px"
                                                    color="#FFFFFF"
                                                >
                                                    End Attendance
                                                </Text>
                                            </Stack>
                                        </Stack>
                                    </Stack>
                                </Stack>
                            </Stack>
                            <Stack
                                justify="flex-start"
                                align="flex-start"
                                spacing="15px"
                                alignSelf="stretch"
                            >
                                <Stack
                                    justify="flex-start"
                                    align="center"
                                    spacing="13px"
                                    alignSelf="stretch"
                                >
                                    <Stack
                                        direction="row"
                                        justify="flex-start"
                                        align="center"
                                        spacing="25px"
                                    />
                                    <Stack
                                        direction="row"
                                        justify="flex-start"
                                        align="flex-start"
                                        spacing="25px"
                                        alignSelf="stretch"
                                    />
                                </Stack>
                                <Stack
                                    direction="row"
                                    justify="flex-start"
                                    align="flex-start"
                                    spacing="4px"
                                    alignSelf="stretch"
                                >
                                    <Stack
                                        direction="row"
                                        justify="flex-start"
                                        align="center"
                                        spacing="25px"
                                    />
                                    <Stack
                                        justify="flex-start"
                                        align="center"
                                        spacing="0px"
                                        width="95px"
                                    >
                                        <Stack
                                            paddingX="8px"
                                            paddingY="13px"
                                            direction="row"
                                            justify="flex-start"
                                            align="center"
                                            spacing="10px"
                                            height="76px"
                                            alignSelf="stretch"
                                        >
                                            <Stack
                                                justify="flex-start"
                                                align="center"
                                                spacing="0px"
                                                width="95px"
                                                boxShadow="0px 2px 4px 0px rgba(0, 0, 0, 0.25)"
                                            >
                                            </Stack>
                                            <Box
                                                borderRadius="8px"
                                                height="68px"
                                                width={"auto"}
                                                alignSelf="stretch"
                                                alignContent={"center"}
                                                boxShadow="0px 4px 4px 0px rgba(0, 0, 0, 0.25)"
                                                background="#FFFFFF"
                                            >
                                                <Text
                                                    fontFamily="Inter"
                                                    lineHeight="1.4"
                                                    fontWeight="semibold"
                                                    fontSize="16px"
                                                    color="#313131"
                                                    width="78px"
                                                    height="42px"
                                                    textAlign="center"
                                                >
                                                    John Doe
                                                    <Box color="#7E3BB5">
                                                        Present
                                                    </Box>
                                                </Text>
                                            </Box>

                                        </Stack>
                                    </Stack>
                                    <Stack
                                        direction="row"
                                        justify="flex-start"
                                        align="center"
                                        spacing="25px"
                                    />
                                </Stack>
                            </Stack>
                        </Stack>
                    </Stack>
                    <Stack
                        paddingX="13px"
                        paddingY="14px"
                        borderRadius="10px"
                        justify="flex-start"
                        align="flex-start"
                        spacing="10px"
                        width="702px"
                        height="689px"
                        maxWidth="100%"
                        background="#313131"
                        boxShadow="0px 4px 4px 0px rgba(0, 0, 0, 0.25)"
                    >
                        <Stack
                            justify="flex-start"
                            align="center"
                            spacing="32px"
                            width="675px"
                            maxWidth="100%"
                        >
                            <Stack
                                paddingX="11px"
                                paddingY="5px"
                                borderRadius="10px"
                                justify="flex-start"
                                align="flex-start"
                                spacing="10px"
                                height="46px"
                                alignSelf="stretch"
                                background="#444343"
                            >
                                <Stack
                                    direction="row"
                                    justify="space-between"
                                    align="center"
                                    spacing="390px"
                                    width="653px"
                                    maxWidth="100%"
                                >
                                    <Stack
                                        direction="row"
                                        justify="flex-start"
                                        align="center"
                                        spacing="14px"
                                    >
                                        <Stack
                                            paddingX="7px"
                                            paddingY="9px"
                                            borderRadius="4px"
                                            justify="flex-start"
                                            align="flex-start"
                                            spacing="10px"
                                            width="25px"
                                            height="25px"
                                            background="#313131"
                                        />
                                        <Stack
                                            direction="row"
                                            justify="flex-start"
                                            align="center"
                                            spacing="0px"
                                        >
                                            <Box width="34.82px" height="34.5px" />
                                            <Text
                                                fontFamily="Inter"
                                                fontWeight="bold"
                                                fontSize="26px"
                                                color="#313131"
                                                width="164px"
                                                height="35px"
                                                textAlign="center"
                                            >
                                                Quick Check
                                            </Text>
                                        </Stack>
                                    </Stack>
                                </Stack>
                            </Stack>
                            <Stack
                                justify="flex-start"
                                align="center"
                                spacing="33px"
                                width="564px"
                                maxWidth="100%"
                            >
                                <Stack
                                    paddingX="38px"
                                    paddingY="31px"
                                    borderRadius="10px"
                                    justify="flex-start"
                                    align="flex-start"
                                    spacing="10px"
                                    width="324px"
                                    height="135px"
                                    maxWidth="100%"
                                    background="#444343"
                                    boxShadow="0px 1px 4px 0px rgba(0, 0, 0, 0.25)"
                                >
                                    <Stack
                                        direction="row"
                                        justify="flex-start"
                                        align="flex-start"
                                        spacing="13px"
                                    >
                                        <Stack
                                            justify="flex-start"
                                            align="flex-start"
                                            spacing="4px"
                                            width="218px"
                                        >
                                            <Text
                                                fontFamily="Inter"
                                                fontWeight="medium"
                                                fontSize="20px"
                                                color="#707070"
                                                alignSelf="stretch"
                                            >
                                                CS 3337 - Prof. Abalos
                                            </Text>
                                            <Text
                                                fontFamily="Inter"
                                                fontWeight="medium"
                                                fontSize="18px"
                                                color="#707070"
                                                alignSelf="stretch"
                                            >
                                                Friday 10/15 Class location : FA 218
                                            </Text>
                                        </Stack>
                                    </Stack>
                                </Stack>
                                <Stack
                                    justify="flex-start"
                                    align="center"
                                    spacing="48px"
                                    alignSelf="stretch"
                                >
                                    <Stack
                                        direction="row"
                                        justify="flex-start"
                                        align="center"
                                        spacing="26px"
                                        alignSelf="stretch"
                                    >
                                        <Stack
                                            paddingX="34px"
                                            paddingY="12px"
                                            borderRadius="10px"
                                            justify="flex-start"
                                            align="flex-start"
                                            spacing="10px"
                                            width="269px"
                                            height="170px"
                                            maxWidth="100%"
                                            background="#444343"
                                            boxShadow="0px 1px 4px 0px rgba(0, 0, 0, 0.25)"
                                        >
                                            <Stack
                                                justify="flex-start"
                                                align="center"
                                                spacing="16px"
                                                width="200px"
                                            >
                                                <Text
                                                    fontFamily="Inter"
                                                    fontWeight="semibold"
                                                    fontSize="45px"
                                                    color="#707070"
                                                    height="47px"
                                                    alignSelf="stretch"
                                                    textAlign="center"
                                                >
                                                    Location
                                                </Text>
                                                <Stack
                                                    paddingX="18px"
                                                    paddingY="7px"
                                                    borderRadius="8px"
                                                    direction="row"
                                                    justify="center"
                                                    align="center"
                                                    spacing="10px"
                                                    width="154px"
                                                    height="38px"
                                                    background="#7E3BB5"
                                                    boxShadow="0px 4px 4px 0px rgba(0, 0, 0, 0.25)"
                                                >
                                                    <Text
                                                        fontFamily="Inter"
                                                        fontWeight="medium"
                                                        fontSize="20px"
                                                        color="#313131"
                                                        textAlign="center"
                                                    >
                                                        Get location
                                                    </Text>
                                                </Stack>
                                                <Stack
                                                    direction="row"
                                                    justify="flex-start"
                                                    align="center"
                                                    spacing="7px"
                                                >
                                                    <Text
                                                        fontFamily="Inter"
                                                        fontWeight="medium"
                                                        fontSize="18px"
                                                        color="#707070"
                                                        width="114px"
                                                        height="23px"
                                                        textAlign="center"
                                                    >
                                                        My location{' '}
                                                    </Text>
                                                </Stack>
                                            </Stack>
                                        </Stack>
                                        <Stack
                                            paddingX="35px"
                                            paddingY="12px"
                                            borderRadius="10px"
                                            justify="flex-start"
                                            align="flex-start"
                                            spacing="10px"
                                            width="269px"
                                            height="170px"
                                            maxWidth="100%"
                                            background="#444343"
                                            boxShadow="0px 1px 4px 0px rgba(0, 0, 0, 0.25)"
                                        >
                                            <Stack
                                                justify="flex-start"
                                                align="center"
                                                spacing="19px"
                                                width="198px"
                                            >
                                                <Text
                                                    fontFamily="Inter"
                                                    fontWeight="semibold"
                                                    fontSize="45px"
                                                    color="#707070"
                                                    height="47px"
                                                    alignSelf="stretch"
                                                    textAlign="center"
                                                >
                                                    Code
                                                </Text>
                                                <Stack
                                                    direction="row"
                                                    justify="flex-start"
                                                    align="center"
                                                    spacing="6px"
                                                    alignSelf="stretch"
                                                >
                                                    <Stack
                                                        paddingX="35px"
                                                        borderRadius="4px"
                                                        direction="row"
                                                        justify="center"
                                                        align="center"
                                                        spacing="10px"
                                                        width="154px"
                                                        height="38px"
                                                        background="#707070"
                                                        boxShadow="inset 1px 1px 2px 1px rgba(0, 0, 0, 0.12)"
                                                    >
                                                        <Text
                                                            fontFamily="Inter"
                                                            fontWeight="medium"
                                                            fontSize="20px"
                                                            color="#444343"
                                                            textAlign="center"
                                                        >
                                                            - - - - - -
                                                        </Text>
                                                    </Stack>
                                                    <Stack
                                                        paddingX="9px"
                                                        paddingY="11px"
                                                        borderRadius="8px"
                                                        justify="flex-start"
                                                        align="flex-start"
                                                        spacing="10px"
                                                        width="38px"
                                                        height="38px"
                                                        background="#7E3BB5"
                                                        boxShadow="0px 4px 4px 0px rgba(0, 0, 0, 0.25)"
                                                    />
                                                </Stack>
                                                <Stack
                                                    direction="row"
                                                    justify="flex-start"
                                                    align="center"
                                                    spacing="3px"
                                                >
                                                    <Text
                                                        fontFamily="Inter"
                                                        fontWeight="medium"
                                                        fontSize="18px"
                                                        color="#707070"
                                                        width="110px"
                                                        height="16px"
                                                        textAlign="center"
                                                    >
                                                        Invalid Code
                                                    </Text>
                                                </Stack>
                                            </Stack>
                                        </Stack>
                                    </Stack>
                                    <Stack
                                        justify="flex-start"
                                        align="center"
                                        spacing="9px"
                                        width="269px"
                                        maxWidth="100%"
                                    >
                                        <Text
                                            fontFamily="Inter"
                                            fontWeight="semibold"
                                            fontSize="36px"
                                            color="#707070"
                                            height="47px"
                                            alignSelf="stretch"
                                            textAlign="center"
                                        >
                                            John Doe
                                        </Text>
                                    </Stack>
                                </Stack>
                            </Stack>
                        </Stack>
                    </Stack>
                </Stack>
            </Stack>
        </Stack>


)
}