import {Box, Card, Stack, Text} from "@chakra-ui/react";

export default function Tabs(){
    return(
        <Stack
            paddingX="324px"
            paddingY="178px"
            justify="flex-start"
            align="flex-start"
            spacing="10px"
            width="1512px"
            height="1131px"
            maxWidth="100%"
            background="#F9F9F9"
        >
            <Stack
                justify="flex-start"
                align="center"
                spacing="25px"
                width="864px"
                maxWidth="100%"
            >
                <Stack
                    justify="flex-start"
                    align="center"
                    spacing="32px"
                    alignSelf="stretch"
                >
                    <Text
                        fontFamily="Inter"
                        fontWeight="bold"
                        fontSize="65px"
                        color="#313131"
                        height="157px"
                        alignSelf="stretch"
                        textAlign="center"
                    >
                        An innovating experience that’d fit your need{' '}
                    </Text>
                    <Text
                        fontFamily="Inter"
                        fontWeight="medium"
                        fontSize="24px"
                        color="#707070"
                        height="86px"
                        alignSelf="stretch"
                        textAlign="center"
                    >
                        Designed to fit your needs
                    </Text>
                </Stack>
                <Stack direction="row" justify="flex-start" align="center" spacing="39px">
                    <Stack
                        paddingX="58px"
                        paddingY="29px"
                        borderRadius="10px"
                        direction="row"
                        justify="center"
                        align="center"
                        spacing="10px"
                        width="224px"
                        height="90.19px"
                        background="#BF9BE6"
                        boxShadow="0px 4px 4px 0px rgba(0, 0, 0, 0.25)"
                    >
                        <Text
                            fontFamily="Inter"
                            fontWeight="semibold"
                            fontSize="26px"
                            color="#FFFFFF"
                            textAlign="center"
                        >
                            Simple
                        </Text>
                    </Stack>
                    <Stack
                        padding="24px"
                        borderRadius="10px"
                        direction="row"
                        justify="center"
                        align="center"
                        spacing="10px"
                        width="224px"
                        height="90.19px"
                        background="#7E3BB5"
                        boxShadow="0px 4px 4px 0px rgba(0, 0, 0, 0.25)"
                    >
                        <Text
                            fontFamily="Inter"
                            fontWeight="semibold"
                            fontSize="26px"
                            color="#FFFFFF"
                            textAlign="center"
                        >
                            Customizable
                        </Text>
                    </Stack>
                    <Stack
                        paddingX="39px"
                        paddingY="21px"
                        borderRadius="10px"
                        direction="row"
                        justify="center"
                        align="center"
                        spacing="10px"
                        width="224px"
                        height="90.19px"
                        background="#7E3BB5"
                        boxShadow="0px 4px 4px 0px rgba(0, 0, 0, 0.25)"
                    >
                        <Text
                            fontFamily="Inter"
                            fontWeight="semibold"
                            fontSize="26px"
                            color="#FFFFFF"
                            textAlign="center"
                        >
                            Exportable
                        </Text>
                    </Stack>
                </Stack>
                <Stack
                    paddingX="49px"
                    paddingY="39px"
                    borderRadius="15px"
                    justify="flex-start"
                    align="flex-start"
                    spacing="10px"
                    width="734px"
                    height="359px"
                    maxWidth="100%"
                    background="#FFFFFF"
                    boxShadow="0px 1px 4px 0px rgba(0, 0, 0, 0.25)"
                >
                    <Stack
                        justify="flex-start"
                        align="flex-start"
                        spacing="39px"
                        width="630px"
                        maxWidth="100%"
                    >
                        <Stack
                            direction="row"
                            justify="flex-start"
                            align="center"
                            spacing="57px"
                            alignSelf="stretch"
                        >
                            <Stack
                                paddingX="35px"
                                paddingY="32px"
                                borderRadius="63.5px"
                                direction="row"
                                justify="flex-start"
                                align="center"
                                spacing="10px"
                                width="127px"
                                height="127px"
                                background="#7E3BB5"
                            />
                            <Text
                                fontFamily="Inter"
                                fontWeight="bold"
                                fontSize="32px"
                                color="#313131"
                                width="446px"
                                height="79px"
                                maxWidth="100%"
                            >
                                Intuitive design to maximize your output
                            </Text>
                        </Stack>
                        <Text
                            fontFamily="Inter"
                            lineHeight="1.58"
                            fontWeight="semibold"
                            fontSize="24px"
                            color="#707070"
                            height="111px"
                            alignSelf="stretch"
                        >
                            Quick Check UI has been engineered to be as intuitive as possible
                            for you to enjoy the simple but efficient experience.
                        </Text>
                    </Stack>
                </Stack>
            </Stack>
        </Stack>


)
}