cors:
  allowed-origins: "https://quickcheckapp.org"  # Use the actual URL of your frontend
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

aws:
  s3:
    mock: false

spring:
  datasource:
    url: jdbc:postgresql://awseb-e-32rfmezfrn-stack-awsebrdsdatabase-n4li6bndjdso.cpq0mm06rdoh.us-west-1.rds.amazonaws.com:5432/postgres
    username: quickcheck
    password: password
