server:
  port: 8088
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  datasource:
    url: jdbc:postgresql://awseb-e-9uyxma8zaw-stack-awsebrdsdatabase-xq4ii2zho2p8.cpq0mm06rdoh.us-west-1.rds.amazonaws.com:5432/ebdb
    username: quickcheck
    password: password

  mail:
    host: smtp.gmail.com
    port: 587
    username: quickcheckteam@gmail.com
    password: pcxx bjbt ugbs wwkw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  main:
    web-application-type: servlet